### ISSUE TITLE
Bank Files Not Registering

### ISSUE THREAD

**Issue by JMacC1991** [BlueRaja/Starbank#14]
A lot of bank files it was reading before are no longer being read. For example: The Thing [Revival] now just shows a lightning setting instead of the stats before. This has happened with multiple banks. Anything I can do for the fix? I did try a testing map recently, and theres been an update I guess. Thanks in advance.

**Comment by BlueRaja** [comment]
I just tried the game and I only see the one bank file in the `Banks` folder.  However I didn't play with other people.

Taking a look at the code, it looks like the only bank files should be `TheThing`, `TheThingSettings1`, and `TheThingBackup`, which should all be caught by StarBank.  Do you have an example bank file that's not being caught (the path, filename, and contents, if you can)?

**Comment by JMacC1991** [comment]
So I just booted it back up, and it is working properly now. It was having issues on two separate computers that I play games similarly. I will check the second computer tomorrow morning. What I was seeing for "The Thing Revival" was just a "Lighting" option. It also happened with Oh No It's Zombies Arctic Updated. The map spawned a second file in my bank called "ohnoizload" that simply had "Player" with a drop down tab of "color" instead of the bank (which is quite extensive in stats from the game including rank value). All of my banks are now working fine though, and I didn't do anything to change the program or the computer that worked. 

The pathing I have is "Documents\StarCraft II\Accounts\63040999\1-S2-1-517372\Banks\1-S2-1-3270554". The code of the new file is:
 

    On Sunday, December 5, 2021, 07:38:36 PM CST, BlueRaja ***@***.***> wrote:  
 
 


I just tried the game and I only see the one bank file in the Banks folder. However I didn't play with other people.

Taking a look at the code, it looks like the only bank files should be TheThing, TheThingSettings1, and TheThingBackup, which should all be caught by StarBank. Do you have an example bank file that's not being caught (the path, filename, and contents, if you can)?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JMacC1991** [comment]
Sorry, hit enter. The code of the new Oh No It's Zombies Artic Updated is:
<?xml version="1.0" encoding="utf-8"?>
<Bank version="1">
    <Section name="Player">
        <Key name="Color">
            <Value int="5"/>
        </Key>
    </Section>
    <Signature value="4EFCB0C100095CA0C4FE5EDA2B518222891B0F1B"/>
</Bank>

This was being read rather than the bank for some reason. I did nothing to fix the issue, but the issue is now resolved. Thank you again.
   On Monday, December 6, 2021, 09:43:35 PM CST, Jesse McCammon ***@***.***> wrote:  
 
 So I just booted it back up, and it is working properly now. It was having issues on two separate computers that I play games similarly. I will check the second computer tomorrow morning. What I was seeing for "The Thing Revival" was just a "Lighting" option. It also happened with Oh No It's Zombies Arctic Updated. The map spawned a second file in my bank called "ohnoizload" that simply had "Player" with a drop down tab of "color" instead of the bank (which is quite extensive in stats from the game including rank value). All of my banks are now working fine though, and I didn't do anything to change the program or the computer that worked. 

The pathing I have is "Documents\StarCraft II\Accounts\63040999\1-S2-1-517372\Banks\1-S2-1-3270554". The code of the new file is:
 

    On Sunday, December 5, 2021, 07:38:36 PM CST, BlueRaja ***@***.***> wrote:  
 
 


I just tried the game and I only see the one bank file in the Banks folder. However I didn't play with other people.

Taking a look at the code, it looks like the only bank files should be TheThing, TheThingSettings1, and TheThingBackup, which should all be caught by StarBank. Do you have an example bank file that's not being caught (the path, filename, and contents, if you can)?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by BlueRaja** [comment]
I am also only seeing the one value for "The Thing Revival", because neither of the other two bank files exist.  I imagine I need to get further in the map before they are created.
