### ISSUE TITLE
Why are these files .iap?

### ISSUE THREAD

**Issue by Klientje** [BlueRaja/Starbank#5]
I've used this program before and it was just .exe. Everything I can find online regarding .iap is that it's supposed to be for apple phones and tablets and shit?

**Comment by IzabEwa** [comment]
same issue

**Comment by BlueRaja** [comment]
The .iap files are the source for _creating_ the installer, not the installer itself.

The link was on the d3scene post, but it appears their forums are down.  I'll try to post the installer here when I get a chance.

**Comment by BlueRaja** [comment]
Added to the [releases page](https://github.com/BlueRaja/Starbank/releases/)
