### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by totalschaden** [BlueRaja/Starbank#6]
https://i.imgur.com/PhDrgPg.png

Started a few weeks ago, since then unable to use it. Reinstall/Clearing Banks didnt work

**Comment by SavZaver** [comment]
Same happened to me after i changed my battletag. Idk if thats the case

**Comment by totalschaden** [comment]
I managed to fix it by deleting all Bnet Cached Data & Mapfiles

**Comment by BlueRaja** [comment]
Sounds like it's caused by the presence of a certain map. It's difficult for me to fix without knowing what map causes it.  Does anyone know?

**Comment by totalschaden** [comment]
Just delete everything inside ProgramData\Blizzard Entertainment\Battle.net\Cache

**Comment by SavZaver** [comment]
Welp, clearing cashe doesn't help :'( gotta look for corrupted map

**Comment by SavZaver** [comment]
Ok, i fixed it by deleting all the maps from programdata/blizzard entertainment/sc2/maps and repairing starbank via installer, i'll notice you if i'll find a broken one

**Comment by MRmikimous** [comment]
Hi, i had that same problem and solved it after deleting programdata/blizzard entertainment/battle.net/cache, then started testing what was wrong and found this file. I hope this helps
[Cache.zip](https://github.com/BlueRaja/Starbank/files/6681056/Cache.zip)

**Comment by BlueRaja** [comment]
Thanks! I was able to repro and fix the issue.

Fixed in [v1.9](https://github.com/BlueRaja/Starbank/releases/latest)
